### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by ArchieGu** [kenshohara/3D-ResNets-PyTorch#86]
Hi
I trained the dataset on resnet 34 followed the given cmd in readme, and it ran well, but after I changed the model depth into 50 and 101, it gave me the error.

![screen shot 2018-08-07 at 2 09 37 pm 2](https://user-images.githubusercontent.com/19317957/43758456-b9b163f4-9a4e-11e8-98a9-d85bcc078385.png)

**Comment by junwenchen** [comment]
Hi, did you solve it?

**Comment by zys20172212265** [comment]
@junwenchen @ArchieGu  i meet the same question when use depth 101,do you solve it

**Comment by TengdaHan** [comment]
Hi, I get the same error message, did you solve it?

**Comment by jangho2001us** [comment]
Today, I encountered same issue and I solved by reducing batch size.
I run 3D resnet architecture with 2 V100 GPUs, with batch size 16.

**Comment by sumeetssaurav** [comment]
You could try using
--resnet_shortcut B for model depth other than 18 and 34.

Thank You

**Comment by sbelharbi** [comment]
Hi,
   I am having similar issue using another code. Any pointers on how to fix it? thanks.
```sh
File "../libs/bn.py", line 109, in forward
    self.training, self.momentum, self.eps, self.activation, self.slope)
  File "../libs/functions.py", line 99, in forward
    running_mean.mul_((1 - ctx.momentum)).add_(ctx.momentum * mean)
RuntimeError: CUDA error: an illegal memory access was encountered
```

**Comment by neonb88** [comment]
Over [here](https://github.com/vchoutas/smplify-x/issues/3) they suggested:

### use system python, not conda: 
> ```shell
> /usr/bin/python3 -m venv venv
> ```

I encountered the same issue. Then the problem has been fixed after creating python environment by system python, NOT from anaconda.   (I think he means from a `virtualenv`,  rather than `conda`). 


Hope this solves your problem!  :D  Please reply if it does to help future readers

**Comment by IvanFei** [comment]
I also met this issue with pytorch=0.4.1
And I solve this problem when update pytorch 0.4.1 to 1.2 
hope this will help you.
